/*
# Create support_requests table

1. Purpose
   The PALS theme support site has a merchant support form that currently only
   sends emails via Resend. This migration adds a database table so each support
   request is also persisted — giving the team a searchable record of every
   submission, with reference numbers, categories, statuses and timestamps.

2. New Tables
   - `support_requests`
     - `id` (uuid, primary key, auto-generated)
     - `reference` (text, unique, not null) — human-readable ID like PALS-YYYYMMDD-XXXX
     - `name` (text, not null) — submitter's full name
     - `email` (text, not null) — submitter's email address
     - `store_url` (text, not null) — Shopify store URL
     - `subject` (text, not null) — short subject line
     - `category` (text, not null) — one of the allowed support categories
     - `theme_version` (text) — optional theme version string
     - `page_url` (text) — optional affected page URL
     - `description` (text, not null) — the full issue description
     - `attachment_name` (text) — original filename if an attachment was uploaded
     - `status` (text, not null, default 'open') — request status: open, in_progress, resolved, closed
     - `created_at` (timestamptz, default now()) — submission timestamp

3. Indexes
   - `support_requests_reference_idx` on `reference` for lookups by reference number
   - `support_requests_email_idx` on `email` for finding requests by submitter
   - `support_requests_status_idx` on `status` for filtering by workflow state
   - `support_requests_created_at_idx` on `created_at` for chronological sorting

4. Security
   - Enable RLS on `support_requests`.
   - This is a no-auth public site (no sign-in screen). The frontend uses the
     anon key, so policies must include `anon`.
   - INSERT is allowed for anyone (the support form is public). Validation is
     done in the application layer before insert.
   - SELECT / UPDATE / DELETE are restricted to `authenticated` only — these
     are for the support team accessing the database directly or via a future
     admin interface. The anon-key frontend cannot read or modify records.

5. Important Notes
   - Attachments are NOT stored in the database — only the filename is recorded.
     The file content continues to be sent via email through Resend.
   - The `status` column defaults to 'open' so new requests start in the
     correct workflow state without the frontend needing to set it.
   - The `reference` column is unique and generated by the application before
     insert, ensuring idempotency if the same form is submitted twice.
*/

CREATE TABLE IF NOT EXISTS support_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reference text UNIQUE NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  store_url text NOT NULL,
  subject text NOT NULL,
  category text NOT NULL,
  theme_version text,
  page_url text,
  description text NOT NULL,
  attachment_name text,
  status text NOT NULL DEFAULT 'open',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE support_requests ENABLE ROW LEVEL SECURITY;

-- Public INSERT: the support form is anonymous and public.
DROP POLICY IF EXISTS "anon_insert_support_requests" ON support_requests;
CREATE POLICY "anon_insert_support_requests"
  ON support_requests FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- SELECT/UPDATE/DELETE restricted to authenticated (support team / future admin).
DROP POLICY IF EXISTS "auth_select_support_requests" ON support_requests;
CREATE POLICY "auth_select_support_requests"
  ON support_requests FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "auth_update_support_requests" ON support_requests;
CREATE POLICY "auth_update_support_requests"
  ON support_requests FOR UPDATE
  TO authenticated
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_delete_support_requests" ON support_requests;
CREATE POLICY "auth_delete_support_requests"
  ON support_requests FOR DELETE
  TO authenticated
  USING (true);

CREATE INDEX IF NOT EXISTS support_requests_reference_idx ON support_requests (reference);
CREATE INDEX IF NOT EXISTS support_requests_email_idx ON support_requests (email);
CREATE INDEX IF NOT EXISTS support_requests_status_idx ON support_requests (status);
CREATE INDEX IF NOT EXISTS support_requests_created_at_idx ON support_requests (created_at DESC);